-- CREACION DE BASE DE DATOS
CREATE DATABASE IF NOT EXISTS Covid_Hist;
USE Covid_Hist;

 -- CREACION DE TABLAS FRAGMENTADAS POR REGIONES
 CREATE TABLE datoscovid_sureste (
    FECHA_ACTUALIZACION VARCHAR(15) NULL,
    ID_REGISTRO VARCHAR(15) NOT NULL,
    ORIGEN INT NULL,
    SECTOR INT NULL,
    ENTIDAD_UM VARCHAR(15) NULL,
    SEXO INT NULL,
    ENTIDAD_NAC VARCHAR(15) NULL,
    ENTIDAD_RES VARCHAR(15) NULL,
    MUNICIPIO_RES VARCHAR(15) NULL,
    TIPO_PACIENTE INT NULL,
    FECHA_INGRESO VARCHAR(15) NULL,
    FECHA_SINTOMAS VARCHAR(15) NULL,
    FECHA_DEF VARCHAR(15) NULL,
    INTUBADO INT NULL,
    NEUMONIA INT NULL,
    EDAD VARCHAR(7) NULL,
    NACIONALIDAD INT NULL,
    EMBARAZO INT NULL,
    HABLA_LENGUA_INDIG INT NULL,
    INDIGENA INT NULL,
    DIABETES INT NULL,
    EPOC INT NULL,
    ASMA INT NULL,
    INMUSUPR INT NULL,
    HIPERTENSION INT NULL,
    OTRA_COM INT NULL,
    CARDIOVASCULAR INT NULL,
    OBESIDAD INT NULL,
    RENAL_CRONICA INT NULL,
    TABAQUISMO INT NULL,
    OTRO_CASO INT NULL,
    TOMA_MUESTRA_LAB INT NULL,
    RESULTADO_LAB INT NULL,
    TOMA_MUESTRA_ANTIGENO INT NULL,
    RESULTADO_ANTIGENO INT NULL,
    CLASIFICACION_FINAL INT NULL,
    MIGRANTE INT NULL,
    PAIS_NACIONALIDAD VARCHAR(50) NULL,
    PAIS_ORIGEN VARCHAR(50) NULL,
    UCI VARCHAR(50) NULL,
    PRIMARY KEY (ID_REGISTRO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

select * 
from covid_hist.datoscovid_sureste;	-- PREUBA TABLA REGION SURESTE

CREATE TABLE datoscovid_suroeste (
    FECHA_ACTUALIZACION VARCHAR(15) NULL,
    ID_REGISTRO VARCHAR(15) NOT NULL,
    ORIGEN INT NULL,
    SECTOR INT NULL,
    ENTIDAD_UM VARCHAR(15) NULL,
    SEXO INT NULL,
    ENTIDAD_NAC VARCHAR(15) NULL,
    ENTIDAD_RES VARCHAR(15) NULL,
    MUNICIPIO_RES VARCHAR(15) NULL,
    TIPO_PACIENTE INT NULL,
    FECHA_INGRESO VARCHAR(15) NULL,
    FECHA_SINTOMAS VARCHAR(15) NULL,
    FECHA_DEF VARCHAR(15) NULL,
    INTUBADO INT NULL,
    NEUMONIA INT NULL,
    EDAD VARCHAR(7) NULL,
    NACIONALIDAD INT NULL,
    EMBARAZO INT NULL,
    HABLA_LENGUA_INDIG INT NULL,
    INDIGENA INT NULL,
    DIABETES INT NULL,
    EPOC INT NULL,
    ASMA INT NULL,
    INMUSUPR INT NULL,
    HIPERTENSION INT NULL,
    OTRA_COM INT NULL,
    CARDIOVASCULAR INT NULL,
    OBESIDAD INT NULL,
    RENAL_CRONICA INT NULL,
    TABAQUISMO INT NULL,
    OTRO_CASO INT NULL,
    TOMA_MUESTRA_LAB INT NULL,
    RESULTADO_LAB INT NULL,
    TOMA_MUESTRA_ANTIGENO INT NULL,
    RESULTADO_ANTIGENO INT NULL,
    CLASIFICACION_FINAL INT NULL,
    MIGRANTE INT NULL,
    PAIS_NACIONALIDAD VARCHAR(50) NULL,
    PAIS_ORIGEN VARCHAR(50) NULL,
    UCI VARCHAR(50) NULL,
    PRIMARY KEY (ID_REGISTRO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

select * 
from covid_hist.datoscovid_suroeste;	-- PREUBA TABLA REGION SUROESTE

-- CREACION Y LLENADO DE TABLA ENTIDADES
CREATE TABLE cat_entidades (
    clave VARCHAR(3) NULL,
    entidad VARCHAR(150) NULL,
    abreviatura VARCHAR(3) NULL
);

INSERT INTO cat_entidades (clave, entidad, abreviatura) VALUES
('01', 'AGUASCALIENTES', 'AS'),
('02', 'BAJA CALIFORNIA', 'BC'),
('03', 'BAJA CALIFORNIA SUR', 'BS'),
('04', 'CAMPECHE', 'CC'),
('05', 'COAHUILA DE ZARAGOZA', 'CL'),
('06', 'COLIMA', 'CM'),
('07', 'CHIAPAS', 'CS'),
('08', 'CHIHUAHUA', 'CH'),
('09', 'CIUDAD DE MÉXICO', 'DF'),
('10', 'DURANGO', 'DG'),
('11', 'GUANAJUATO', 'GT'),
('12', 'GUERRERO', 'GR'),
('13', 'HIDALGO', 'HG'),
('14', 'JALISCO', 'JC'),
('15', 'MÉXICO', 'MC'),
('16', 'MICHOACÁN DE OCAMPO', 'MN'),
('17', 'MORELOS', 'MS'),
('18', 'NAYARIT', 'NT'),
('19', 'NUEVO LEÓN', 'NL'),
('20', 'OAXACA', 'OC'),
('21', 'PUEBLA', 'PL'),
('22', 'QUERÉTARO', 'QT'),
('23', 'QUINTANA ROO', 'QR'),
('24', 'SAN LUIS POTOSÍ', 'SP'),
('25', 'SINALOA', 'SL'),
('26', 'SONORA', 'SR'),
('27', 'TABASCO', 'TC'),
('28', 'TAMAULIPAS', 'TS'),
('29', 'TLAXCALA', 'TL'),
('30', 'VERACRUZ DE IGNACIO DE LA LLAVE', 'VZ'),
('31', 'YUCATÁN', 'YN'),
('32', 'ZACATECAS', 'ZS'),
('36', 'ESTADOS UNIDOS MEXICANOS', 'EUM'),
('97', 'NO APLICA', 'NA'),
('98', 'SE IGNORA', 'SI'),
('99', 'NO ESPECIFICADO', 'NE');

select * 
from covid_hist.cat_entidades;	-- PREUBA TABLA ENTIDADES
